# Generated by Django 3.2.9 on 2021-11-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameUser', models.CharField(max_length=20, null=True)),
                ('Apellidos', models.CharField(max_length=60, null=True)),
                ('Nick', models.CharField(max_length=30, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
